<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use frontend\assets\AutoTabsAsset;

AutoTabsAsset::register($this);
$this->title = 'Sistem Anjungan - Jadwal';
?>

<div class="container">
<div class="wrap-content" style="color:#80b3ff;">
    <div id="jadwal-seminar">
        <ul>
            <li><a href="#seminar-kmm">Seminar KMM</a></li>
            <li><a href="#seminar-proposal">Seminar Proposal</a></li>
            <li><a href="#seminar-hasil">Seminar Hasil</a></li>
            <li><a href="#seminar-ta">Seminar TA</a></li>
        </ul>
        <div id="seminar-kmm" style="overflow: auto;">
            <h3>Seminar KMM</h3>
            <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>League</th>
                    <th>Country</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                </tbody>
            </table>
        </div>
        <div id="seminar-proposal">
           <h3>Seminar Proposal</h3>
            <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>League</th>
                    <th>Country</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                </tbody>
            </table>
        </div>
        <div id="seminar-hasil">
            <h3>Seminar Hasil</h3>
            <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>League</th>
                    <th>Country</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                </tbody>
            </table>
        </div>
        <div id="seminar-ta">
            <h3>Seminar TA</h3>
            <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>League</th>
                    <th>Country</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                  <tr>
                    <td>asdsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                    <td>asdadsada</td>
                  </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>


<?php

#### Tabs Setting ####
$js = <<< JS
var tabs = $('#jadwal-seminar');
    tabs.responsiveTabs({
        rotate: false,
        startCollapsed: 'accordion',
        collapsible: 'accordion',
        setHash: true,
        animation : 'slide',
        animationQueue: 'true',
        duration : 300,
        scrollToAccordion : true,
        scrollToAccordionOffset: true,

    });

JS;
$this->registerJS($js);

#### Change menu title ####
$js = <<< JS
$( '#cd-dropdown option[data-title-id="jadwal seminar"]' ).attr('selected','');
JS;
$this->registerJS($js);
?>